export const CREATE_ISSUE_REQUEST = 'CREATE_ISSUE_REQUEST';
export const CREATE_ISSUE_SUCCESSED = 'CREATE_ISSUE_SUCCESSED';
export const CREATE_ISSUE_FAILED = 'CREATE_ISSUE_FAILED';

export const DELETE_ISSUE_REQUEST = 'DELETE_ISSUE_REQUEST';
export const DELETE_ISSUE_SUCCESSED = 'DELETE_ISSUE_SUCCESSED';
export const DELETE_ISSUE_FAILED = 'DELETE_ISSUE_FAILED';

export const OPEN_ISSUE_EDITOR = 'OPEN_ISSUE_EDITOR';

export const GET_ISSUE_REQUEST = 'GET_ISSUE_REQUEST';
export const GET_ISSUE_SUCCESSED = 'GET_ISSUE_SUCCESSED';
export const GET_ISSUE_FAILED = 'GET_ISSUE_FAILED';

export const EDIT_ISSUE_REQUEST = 'EDIT_ISSUE_REQUEST';
export const EDIT_ISSUE_SUCCESSED = 'EDIT_ISSUE_SUCCESSED';
export const EDIT_ISSUE_FAILED = 'EDIT_ISSUE_FAILED';

export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESSED = 'FETCH_ISSUES_SUCCESSED';
export const FETCH_ISSUES_FAILED = 'FETCH_ISSUES_FAILED';

export const DOWNLOAD_ATTACHMENT_REQUEST = 'DOWNLOAD_ATTACHMENT_REQUEST';
export const DOWNLOAD_ATTACHMENT_SUCCESSED = 'DOWNLOAD_ATTACHMENT_SUCCESSED';
export const DOWNLOAD_ATTACHMENT_FAILED = 'DOWNLOAD_ATTACHMENT_FAILED';

export const UPLOAD_FILES_REQUEST = 'UPLOAD_FILES_REQUEST';

export const UPLOAD_PROGRESS_CHANGED = 'UPLOAD_PROGRESS_CHANGED';

export const UPLOAD_PAUSED = 'UPLOAD_PAUSED';
export const UPLOAD_PAUSED_SUCCESSED = 'UPLOAD_PAUSED_SUCCESSED';
export const UPLOAD_PAUSED_FAILED = 'UPLOAD_PAUSED_FAILED';

export const UPLOAD_RUNNING = 'UPLOAD_RUNNING';
export const UPLOAD_RUNNING_SUCCESSED = 'UPLOAD_RUNNING_SUCCESSED';
export const UPLOAD_RUNNING_FAILED = 'UPLOAD_RUNNING_FAILED';

export const UPLOAD_CANCEL = 'UPLOAD_CANCEL';
export const UPLOAD_CANCEL_SUCCESSED = 'UPLOAD_CANCEL_SUCCESSED';
export const UPLOAD_CANCEL_FAILED = 'UPLOAD_CANCEL_FAILED';

export const ISSUES_CLOSE_NOTIFICATION = 'ISSUES_CLOSE_NOTIFICATION';

export const ISSUE_ANSWER_REQUEST = 'ISSUE_ANSWER_REQUEST';
export const ISSUE_ANSWER_SUCCESSED = 'ISSUE_ANSWER_SUCCESSED';
export const ISSUE_ANSWER_FAILED = 'ISSUE_ANSWER_FAILED';
