export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESSED = 'USER_LOGIN_SUCCESSED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESSED = 'USER_LOGOUT_SUCCESSED';
export const USER_LOGOUT_FAILED = 'USER_LOGOUT_FAILED';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESSED = 'USER_CREATE_SUCCESSED';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESSED = 'USER_DELETE_SUCCESSED';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESSED = 'USER_UPDATE_SUCCESSED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_SUCCESSED = 'UPDATE_PASSWORD_SUCCESSED';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESSED = 'RESET_PASSWORD_SUCCESSED';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const UPDATE_EMAIL_REQUEST = 'UPDATE_EMAIL_REQUEST';
export const UPDATE_EMAIL_SUCCESSED = 'UPDATE_EMAIL_SUCCESSED';
export const UPDATE_EMAIL_FAILED = 'UPDATE_EMAIL_FAILED';